apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dmqttdemo-helmrelease
  namespace: default
spec:
  releaseName: dmqttdemo-dev
  chart:
    repository: oci://dmqttdemo.azurecr.io/helm/dmqtt
  interval: 5m
  targetNamespace: default
  install:
    remediation:
      retries: 3
  values:
    broker:
      frontend:
        replicas: 1
