apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: dmqttdemo.azurecr.io/identity/test/publisher:latest
          volumeMounts:
            - name: iotedge-spiffe-agent-socket
              mountPath: /run/iotedge/sockets/           
        - name: iotedge-spiffe-agent-socket
          hostPath:
            path: /run/iotedge/sockets/
            type: DirectoryOrCreate
