apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: subscriber
          image: dmqttdemo.azurecr.io/identity/test/subscriber:latest
          volumeMounts:
            - name: iotedge-spiffe-agent-socket
              mountPath: /run/iotedge/sockets/           
        - name: iotedge-spiffe-agent-socket
          hostPath:
            path: /run/iotedge/sockets/
            type: DirectoryOrCreate
