apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dmqttdemo-helmrelease
  namespace: dmqttdemo
spec:
  releaseName: dmqttdemo-dev
  chart:
    spec:
      chart: dmqtt
      sourceRef:
        kind: HelmRepository
        name: my-repository
        namespace: dmqttdemo
  interval: 5m
