apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dmqttdemo-helmrelease
  namespace: dmqttdemo
spec:
  releaseName: dmqttdemo-dev
  chart:
    spec:
      chart: dmqtt
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: my-repository
        namespace: dmqttdemo
  interval: 5m
  values:
    replicaCount: 2
    broker:
      frontend:
        replicas: 1
