apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dmqttdemo-helmrelease
  namespace: dmqttdemo
spec:
  releaseName: dmqttdemo-dev
  chart:
    spec:
      chart: dmqttdemo
      interval: 1
      sourceRef:
        kind: HelmRepository
        name: my-repository
        namespace: dmqttdemo
  interval: 1m
  timeout: 10m
  values:
    broker:
      frontend:
        replicas: 1
