apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: e4k-helmrelease
  namespace: e4k
spec:
  releaseName: e4k-dev
  chart:
    spec:
      chart: gitaz-e4k
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: e4k-repository
        namespace: e4k
  interval: 5m
