apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: e4k-helmrelease
  namespace: e4k
spec:
  releaseName: e4k-dev
  chart:
    repository: https://edgecharts.azurecr.io/helm/v1/repo/
    name: gitaz-e4k
    version: 0.1.0
  interval: 5m
